version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging to Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 294380780117.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=294380780117.dkr.ecr.us-east-1.amazonaws.com/devils
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image
      - docker build --tag $REPOSITORY_URI:$COMMIT_HASH .
            
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker image
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Writing image definition files
      - printf '[{"name":"devils-task","imageUri":"%s"}]' $REPOSITORY_URI:$COMMIT_HASH > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: 
    - imagedefinitions.json
